-- MySQL Script generated by MySQL Workbench
-- 03/26/17 21:04:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dev_team
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dev_team` ;

-- -----------------------------------------------------
-- Schema dev_team
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev_team` DEFAULT CHARACTER SET utf8 ;
USE `dev_team` ;

-- -----------------------------------------------------
-- Table `dev_team`.`CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_team`.`CUSTOMER` ;

CREATE TABLE IF NOT EXISTS `dev_team`.`CUSTOMER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_team`.`MANAGER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_team`.`MANAGER` ;

CREATE TABLE IF NOT EXISTS `dev_team`.`MANAGER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_team`.`TERMS_OF_REFERENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_team`.`TERMS_OF_REFERENCE` ;

CREATE TABLE IF NOT EXISTS `dev_team`.`TERMS_OF_REFERENCE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TERMS_OF_REFERENCE_CUSTOMER1_idx` (`customer_id` ASC),
  INDEX `fk_TERMS_OF_REFERENCE_MANAGER1_idx` (`manager_id` ASC),
  CONSTRAINT `fk_TERMS_OF_REFERENCE_CUSTOMER1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dev_team`.`CUSTOMER` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_TERMS_OF_REFERENCE_MANAGER1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `dev_team`.`MANAGER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_team`.`TASK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_team`.`TASK` ;

CREATE TABLE IF NOT EXISTS `dev_team`.`TASK` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `terms_of_reference_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TASK_TERMS_OF_REFERENCE_idx` (`terms_of_reference_id` ASC),
  CONSTRAINT `fk_TASK_TERMS_OF_REFERENCE`
    FOREIGN KEY (`terms_of_reference_id`)
    REFERENCES `dev_team`.`TERMS_OF_REFERENCE` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_team`.`PROJECT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_team`.`PROJECT` ;

CREATE TABLE IF NOT EXISTS `dev_team`.`PROJECT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `terms_of_reference_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PROJECT_TERMS_OF_REFERENCE1_idx` (`terms_of_reference_id` ASC),
  CONSTRAINT `fk_PROJECT_TERMS_OF_REFERENCE1`
    FOREIGN KEY (`terms_of_reference_id`)
    REFERENCES `dev_team`.`TERMS_OF_REFERENCE` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_team`.`DEVELOPER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_team`.`DEVELOPER` ;

CREATE TABLE IF NOT EXISTS `dev_team`.`DEVELOPER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `project_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DEVELOPER_PROJECT_idx` (`project_id` ASC),
  CONSTRAINT `fk_DEVELOPER_PROJECT`
    FOREIGN KEY (`project_id`)
    REFERENCES `dev_team`.`PROJECT` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_team`.`TIMESHEET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_team`.`TIMESHEET` ;

CREATE TABLE IF NOT EXISTS `dev_team`.`TIMESHEET` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `project_id` INT NOT NULL,
  `developer_id` INT NOT NULL,
  `time` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TIMESHEET_PROJECT1_idx` (`project_id` ASC),
  INDEX `fk_TIMESHEET_DEVELOPER_idx` (`developer_id` ASC),
  CONSTRAINT `fk_TIMESHEET_PROJECT`
    FOREIGN KEY (`project_id`)
    REFERENCES `dev_team`.`PROJECT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_TIMESHEET_DEVELOPER`
    FOREIGN KEY (`developer_id`)
    REFERENCES `dev_team`.`DEVELOPER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_team`.`INVOICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_team`.`INVOICE` ;

CREATE TABLE IF NOT EXISTS `dev_team`.`INVOICE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_INVOICE_PROJECT_idx` (`project_id` ASC),
  CONSTRAINT `fk_INVOICE_PROJECT`
    FOREIGN KEY (`project_id`)
    REFERENCES `dev_team`.`PROJECT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
